spring:
  profiles:
    default: local

springdoc:
  swagger-ui:
    path: /api/docs
  api-docs:
    path: /api/v3/api-docs

auth:
  token:
    secret: ${AUTH_TOKEN_SECRET}
    access-token-validity-seconds: ${AUTH_ACCESS_TOKEN_VALIDITY_SECONDS:3600}
    refresh-token-validity-seconds: ${AUTH_REFRESH_TOKEN_VALIDITY_SECONDS:1209600}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}
